In [2]:
print(name)

Vasya


In [1]:
age, name, type = 24, "Vasya", "male"

In [3]:
list_two = list(range(1, 4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)

[2, 12, 36]


In [6]:
import numpy as np

array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)


[ 2 12 36]


In [7]:
import numpy as np

#Creating mulit dimensional array
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

multi_array = np.array([x,y,z], dtype = np.int16)
print(multi_array)
print(multi_array.shape)

#Getting a number
multi_array[1,2]

#Printing data type
print(multi_array.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
int16


In [8]:
#Slicing
import numpy as np

x = np.arange(1,10)
print(x)
x[2:7]

[1 2 3 4 5 6 7 8 9]


array([3, 4, 5, 6, 7])

In [9]:
#Reshaping

import numpy as np

x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
import numpy as np

x = np.arange(18).reshape(3,2,3)
print(x)

x[1, 0:2, 2]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


array([ 8, 11])

In [14]:
import numpy as np

x = np.arange(18).reshape(3,2,3)
print(x)

comparison_operator = x > 5
x[comparison_operator]

#max and min
x.max()
x.min()

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


17

In [18]:
import numpy as np

x = np.arange(18).reshape(3,2,3)

#Modifying original array
ravelled_array = x.ravel()
print(ravelled_array)
#Return copy of the array
flattened_array = x.flatten()
print(flattened_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [1]:
import numpy as np

y = np.arange(9)
y.shape = [3,3]
#Transpose changing rows and colums place
print(y.T)
print(" ")

#Zeroes
print(np.zeros((3,2), dtype=int))
print(" ")

#Diagonal matrix
print(np.eye(3))

print(" ")
np.random.rand(4,4)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
 
[[0 0]
 [0 0]
 [0 0]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 


array([[0.66851731, 0.42009447, 0.20294778, 0.66758424],
       [0.82417469, 0.77485677, 0.39980096, 0.87885442],
       [0.99751452, 0.17256893, 0.56909561, 0.07558974],
       [0.86583509, 0.8774069 , 0.27669621, 0.40732946]])

In [14]:
import numpy as np

#Stacking by second axis horizontali
x = np.arange(4).reshape(2,2)

y=np.arange(4,8).reshape(2,2)

#tuple np.column_stak() do the sime for multi dimensional arrays for 1D array stack it along 1'st axis(verticali)
z = np.hstack((x,y))
print(z)

w = np.concatenate((x,y), axis = 1)
print(" ")
print(w)

print(" ")
print("X- array ")
print(" ")
print(x)
print(" ")
print("y- array ")
print(" ")
print(y)
depth_stack = np.dstack((x,y))
print("D stack ")
print(depth_stack)

[[0 1 4 5]
 [2 3 6 7]]
 
[[0 1 4 5]
 [2 3 6 7]]
 
X- array 
 
[[0 1]
 [2 3]]
 
y- array 
 
[[4 5]
 [6 7]]
D stack 
[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [1]:
import numpy as np

#Matrix multiplication (numb of colums in matrix A must be equal to number of rows in matrix B )

matrix_a = np.matrix([0,3,3,4,7,3]).reshape(2,3)
matrix_b = np.matrix([0,-3,-5,8,12,2]).reshape(3,2)
matrix_a * matrix_b

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray
